url audio
Piasy/RxAndroidAudio pull request #19
Opened 2016-12-12 03:52 UTC by XanthusL

mediaPlayer.setDataSource("url");

2016-12-12 04:03 UTC, Piasy requested changes

2016-12-12 04:03 UTC, Piasy commented on rxandroidaudio/src/main/java/com/github/piasy/rxandroidaudio/RxAudioPlayer.java
> +        } else if (config.mType == PlayConfig.TYPE_URL && config.url != null &&
Thanks for your PR!

Maybe we can turn this if-else-if into switch, and do some common check before it.

And you can check url with `TextUtil.isEmpty`.

2016-12-12 04:03 UTC, Piasy commented on rxandroidaudio/src/main/java/com/github/piasy/rxandroidaudio/PlayConfig.java
> +    final String url;
And could you please rename this field into `mUrl`?

2016-12-13 06:25 UTC, Piasy requested changes

2016-12-13 06:25 UTC, Piasy commented on rxandroidaudio/src/main/java/com/github/piasy/rxandroidaudio/PlayConfig.java
> +        String url;
This field please.

2016-12-13 06:25 UTC, Piasy commented on rxandroidaudio/src/main/java/com/github/piasy/rxandroidaudio/RxAudioPlayer.java
> +        switch (config.mType) {
I'm just wondering whether we could encapsulate the parameter check into `PlayConfig` it self, e.g. `isArgumentIllegal()`, so we don't need check it inside the switch, and no more fall through in each case.

If you don't want to do this update, it's totally ok, I'll clean it up and cut a new release :)

2016-12-13 06:27 UTC, liyiheng commented on rxandroidaudio/src/main/java/com/github/piasy/rxandroidaudio/PlayConfig.java
> +        String url;
okay

2016-12-13 06:45 UTC, XanthusL commented on rxandroidaudio/src/main/java/com/github/piasy/rxandroidaudio/RxAudioPlayer.java
> +        switch (config.mType) {
I didn't clone the  repository, just downloaded the zip file.
So I have to commit on the web file by file. It's great if you can do this update.

In my opinion, the parameter check in  `PlayConfig` will make the code clean, but there wolud be two `switch(mType)` , one in `PlayConfig` , and one in `play()`.
Maybe `isArgumentIllegal()` can be implemented as 3 methods.

2016-12-13 07:11 UTC, Piasy commented on rxandroidaudio/src/main/java/com/github/piasy/rxandroidaudio/RxAudioPlayer.java
> +        switch (config.mType) {
No problem, I think two switch is ok.

2016-12-13 07:12 UTC, merged

2016-12-13 08:30 UTC, Piasy commented
@XanthusL I've just update two commits, and cut `v1.4.0`.