Migrating to Androidx
Piasy/RxAndroidAudio pull request #59
Opened 2018-11-25 13:50 UTC by rurimo

Migrating to Androidx

2018-11-26 00:07 UTC, Piasy requested changes

2018-11-26 00:07 UTC, Piasy commented on AudioProcessor/build.gradle
> +    buildToolsVersion '28.0.3'
Why not change `androidBuildToolsVersion` in root build.gradle?

2018-11-26 00:07 UTC, Piasy commented on app/build.gradle
> +    buildToolsVersion '28.0.3'
Why not change `androidBuildToolsVersion` in root build.gradle?

2018-11-26 00:07 UTC, Piasy commented on app/build.gradle
> +    implementation 'androidx.appcompat:appcompat:1.0.2'
Why not add an `androidXVersion` in root build.gradle?

2018-11-26 00:07 UTC, Piasy commented on app/src/main/java/com/github/piasy/rxandroidaudio/example/FileActivity.java
> +        mIvVoiceIndicators.add((ImageView) findViewById(R.id.mIvVoiceIndicator1));
Do we still need the type cast?

2018-11-26 00:07 UTC, Piasy commented on rxandroidaudio/src/main/java/com/github/piasy/rxandroidaudio/PlayConfig.java
> -        /**
Why do you delete this comment?

2018-11-26 00:08 UTC, Piasy commented
Thanks for your contribution! I have some comments on your changes, please address it so that I can merge it :)

2018-11-26 07:48 UTC, rurimo commented
@Piasy 
Thank you for your PR review.
I refactored them by your comments and some example codes. :)

2018-11-27 15:08 UTC, merged

2018-11-27 15:11 UTC, Piasy commented
v1.6.0 is released, check it out :)